# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e35d42d531a4aa222ea18487e5fa61914337d02d6305dea3bbaf6d82469459afd41194867cc790b2dc6945f1af0424032556cf97b21d2e8b34e87d752da7aa2a

test:
  secret_key_base: fd7a0c8296075e3fc0577306704c56ce26e6e5ea1cab4362dde5443812b82dc168a1f44cb7869940f14f22ac2739a4ed91303436c3605961f9fa7275477b76c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
